# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.AddBtn = QtWidgets.QPushButton(Form)
        self.AddBtn.setGeometry(QtCore.QRect(404, 528, 371, 23))
        self.AddBtn.setObjectName("AddBtn")
        self.DelBtn = QtWidgets.QPushButton(Form)
        self.DelBtn.setGeometry(QtCore.QRect(21, 528, 371, 23))
        self.DelBtn.setObjectName("DelBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.AddBtn.setText(_translate("Form", "Добавить"))
        self.DelBtn.setText(_translate("Form", "Удалить"))
